[project]
name = "hanlp2-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hanlp>=2.1.0",
    "hanlp-restful>=0.0.24",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
